# Generated by Django 2.2 on 2019-11-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='descriptions',
            field=models.TextField(default='This is a test descriptions xaxa'),
            preserve_default=False,
        ),
    ]
