# Generated by Django 2.2 on 2019-12-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20191216_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='image', upload_to=''),
            preserve_default=False,
        ),
    ]
