# Generated by Django 2.2 on 2019-12-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20191217_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='descriptions',
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='payment'),
            preserve_default=False,
        ),
    ]
